# Generated by Django 5.1.4 on 2024-12-06 03:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=30)),
                ('avgCtnPrice', models.FloatField(default=0)),
                ('stdCtnCost', models.FloatField(default=0)),
                ('pricePerPound', models.FloatField(default=0)),
                ('netWeightChile', models.FloatField(default=0)),
                ('netWeightDomestic', models.FloatField(default=0)),
                ('packingCharge', models.FloatField(default=0)),
                ('pallets', models.FloatField(default=0)),
                ('profitPerBag', models.FloatField(default=0, null=True)),
                ('promo', models.FloatField(default=0)),
            ],
        ),
    ]
